# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = { version = "0.10.2", default-features = false }

[profile.release]
lto = true

[package]
name = "rust"
version = "0.1.0"
crate-type = ["cdylib"]
